name: sign_up
description: "A new Flutter project for user sign-up."

publish_to: 'none'  # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8  # For iOS-style icons
  http: ^0.13.6
  shared_preferences: ^2.2.0
  path: ^1.8.0       # or the latest version
  crypto: ^3.0.0 
  url_launcher: ^6.3.1
  firebase_core: ^3.12.0
  firebase_messaging: ^15.2.3
  intl: ^0.20.2
  open_file: ^3.5.10
  path_provider: ^2.1.5
  web_socket_channel: ^3.0.2
  flutter_local_notifications: ^18.0.1
  flutter_awesome_alert_box: ^2.0.0
  crypt: ^4.3.1
  record: ^5.1.2
  audioplayers: ^6.4.0
  permission_handler: ^11.3.1

  

 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true 

  assets:
    - assets/image/pi.png
    - assets/image/nopro.jpg  


flutter_icons:
   image_path: "assets/image/tick.png"
   android: true
   ios:  true


